name: Cleanup Old Releases

on:
  release:
    types: [published]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all but the last 5 releases (keep tags)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all releases sorted by creation date (oldest first)
          releases=$(gh api repos/${{ github.repository }}/releases --paginate --jq 'sort_by(.created_at) | .[].id')

          count=$(echo "$releases" | wc -l)

          if [ "$count" -le 5 ]; then
            echo "Nothing to delete — only $count releases exist."
            exit 0
          fi

          # Determine IDs to delete (all but the last 5)
          ids_to_delete=$(echo "$releases" | head -n -5)

          for id in $ids_to_delete; do
            echo "Deleting release ID $id (tag will remain)"
            gh api -X DELETE repos/${{ github.repository }}/releases/$id
          done
